### ISSUE TITLE
Multiple spelling columns

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#601]
Possibly related to #588 -- when loading the running text sample corpus, two spelling columns are created [in the running text view; the corpus window is fine], but the first is blank:

![image](https://cloud.githubusercontent.com/assets/7317450/18145248/3cbb5234-6f7f-11e6-8897-6fc9688919d1.png)

**Comment by kchall** [comment]
Possibly related: when loading in the ilg_sample corpus, the names of the columns aren't copied over from the parsing preview dialogue box (e.g., "spelling" and "transcription"); instead, they are called "line 1" and "line 2" in the corpus window. And, in the running text window, there is an extra, blank "line 2" column that probably should be "transcription" (and not blank).

The parsing preview window:

![image](https://cloud.githubusercontent.com/assets/7317450/18145600/ce0084c0-6f80-11e6-899d-613340e5a7c6.png)

And the resulting corpus:
![image](https://cloud.githubusercontent.com/assets/7317450/18145578/afd3582e-6f80-11e6-84de-177bbc006dcf.png)

**Comment by jsmackie** [comment]
I haven't solved the multiple spelling/empty transcription problem yet, but I have fixed the ILG bug that mislabels the column headings.

**Comment by kchall** [comment]
Wait, as you say above, "I haven't solved the multiple spelling/empty transcription problem yet" -- and indeed, this is still happening, so I'm going to re-open this issue.
